//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"encoding/json"

	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *E2ETestRun) DeepCopyInto(out *E2ETestRun) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new E2ETestRun.
func (in *E2ETestRun) DeepCopy() *E2ETestRun {
	if in == nil {
		return nil
	}
	out := new(E2ETestRun)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *E2ETestRun) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *E2ETestRunList) DeepCopyInto(out *E2ETestRunList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]E2ETestRun, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new E2ETestRunList.
func (in *E2ETestRunList) DeepCopy() *E2ETestRunList {
	if in == nil {
		return nil
	}
	out := new(E2ETestRunList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *E2ETestRunList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *E2ETestRunSpec) DeepCopyInto(out *E2ETestRunSpec) {
	*out = *in
	in.Runner.DeepCopyInto(&out.Runner)
	if in.TestCases != nil {
		in, out := &in.TestCases, &out.TestCases
		*out = make([]TestCase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new E2ETestRunSpec.
func (in *E2ETestRunSpec) DeepCopy() *E2ETestRunSpec {
	if in == nil {
		return nil
	}
	out := new(E2ETestRunSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *E2ETestRunStatus) DeepCopyInto(out *E2ETestRunStatus) {
	*out = *in
	if in.TestCases != nil {
		in, out := &in.TestCases, &out.TestCases
		*out = make([]TestCaseStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new E2ETestRunStatus.
func (in *E2ETestRunStatus) DeepCopy() *E2ETestRunStatus {
	if in == nil {
		return nil
	}
	out := new(E2ETestRunStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *E2ETestSpecification) DeepCopyInto(out *E2ETestSpecification) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new E2ETestSpecification.
func (in *E2ETestSpecification) DeepCopy() *E2ETestSpecification {
	if in == nil {
		return nil
	}
	out := new(E2ETestSpecification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *E2ETestSpecification) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *E2ETestSpecificationList) DeepCopyInto(out *E2ETestSpecificationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]E2ETestSpecification, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new E2ETestSpecificationList.
func (in *E2ETestSpecificationList) DeepCopy() *E2ETestSpecificationList {
	if in == nil {
		return nil
	}
	out := new(E2ETestSpecificationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *E2ETestSpecificationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *E2ETestSpecificationSpec) DeepCopyInto(out *E2ETestSpecificationSpec) {
	*out = *in
	if in.TestCases != nil {
		in, out := &in.TestCases, &out.TestCases
		*out = make([]TestCase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new E2ETestSpecificationSpec.
func (in *E2ETestSpecificationSpec) DeepCopy() *E2ETestSpecificationSpec {
	if in == nil {
		return nil
	}
	out := new(E2ETestSpecificationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *E2ETestSpecificationStatus) DeepCopyInto(out *E2ETestSpecificationStatus) {
	*out = *in
	if in.LastExecutionTime != nil {
		in, out := &in.LastExecutionTime, &out.LastExecutionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new E2ETestSpecificationStatus.
func (in *E2ETestSpecificationStatus) DeepCopy() *E2ETestSpecificationStatus {
	if in == nil {
		return nil
	}
	out := new(E2ETestSpecificationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Runner) DeepCopyInto(out *Runner) {
	*out = *in
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Runner.
func (in *Runner) DeepCopy() *Runner {
	if in == nil {
		return nil
	}
	out := new(Runner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestCase) DeepCopyInto(out *TestCase) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestCase.
func (in *TestCase) DeepCopy() *TestCase {
	if in == nil {
		return nil
	}
	out := new(TestCase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestCaseStatus) DeepCopyInto(out *TestCaseStatus) {
	*out = *in
	if in.Exports != nil {
		in, out := &in.Exports, &out.Exports
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
	if in.DebugInfo != nil {
		in, out := &in.DebugInfo, &out.DebugInfo
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestCaseStatus.
func (in *TestCaseStatus) DeepCopy() *TestCaseStatus {
	if in == nil {
		return nil
	}
	out := new(TestCaseStatus)
	in.DeepCopyInto(out)
	return out
}
